version: "3.8"

configs:
  acquis.yaml:
    content: |
      filenames:
        - /var/log/traefik/*
      labels:
        type: traefik
  appsec.yaml:
    content: |
      appsec_config: crowdsecurity/appsec-default
      labels:
        type: appsec
      listen_addr: 0.0.0.0:7422
      source: appsec
services:
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - /var/log/traefik:/var/log/traefik/:ro
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    configs:
      - source: acquis.yaml
        target: /etc/crowdsec/acquis.yaml
      - source: appsec.yaml
        target: /etc/crowdsec/acquis.d/appsec.yaml
    environment:
      COLLECTIONS: >
        crowdsecurity/traefik crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules

    security_opt:
      - no-new-privileges:true

  logrotate:
    image: blacklabelops/logrotate
    container_name: logrotate
    restart: unless-stopped
    volumes:
      - /opt/traefik-logs:/var/log/traefik
      - /opt/logrotate.d/traefik:/etc/logrotate.d/traefik:ro

networks:
  coolify:
    external: true
