version: '3.8'

networks:
  coolify:
    external: true

services:
  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: unless-stopped
    networks:
      - coolify
    volumes:
      - /opt/traefik-logs:/var/log/traefik
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - ./crowdsec/appsec.yaml:/etc/crowdsec/acquis.d/appsec.yaml
    environment:
      COLLECTIONS: >
        crowdsecurity/traefik
        crowdsecurity/appsec-virtual-patching
        crowdsecurity/appsec-generic-rules
    ports:
      # - "8081:8080"  # CrowdSec API (optional) 8080 is used by coolify-proxy
      - "7422:7422"  # AppSec

  logrotate:
    image: blacklabelops/logrotate
    container_name: logrotate
    restart: unless-stopped
    volumes:
      - /opt/traefik-logs:/var/log/traefik
      - ./logrotate/logrotate.conf:/etc/logrotate.conf:ro
    environment:
      - LOGROTATE_INTERVAL=daily
